- schema: jumbo_derived
  table: chat_order_history
  columns:
  - user_id: bigint
    row_computed_at: timestamp
    session_id: string
    landed_at: timestamp
    assigned_at: timestamp
    resolved_at: timestamp
    channel_id: integer
    aht: bigint
    agent_id: bigint
    agent_email: string
    tl_name: string
    tl_email: string
    resolution_tag: string
    lrt: bigint
    rt_lrt: bigint
    status: bigint
    reopen_flag: interger
    fr_given_by: bigint
    agent_frt: bigint
    frt: bigint
    frt_timestamp: bigint
    total_irs: bigint
    good_irs: bigint
    tab_id: bigint
    csat: string
    rated_at: timestamp
    tags: string
    node: string
    order_status: bigint
    reject_message_name: string
    city_name: string
    country_name: string
    res_name: string
    res_id: bigint
    platform: string
    clubbing_flag: integer
    paytm_flag: integer
    hybrid_flag: integer
    otof_flag: integer
    new_user_flag: integer
    rpf_flag: integer
    gold_order_flag: integer
    karma_score: string
    ps_segment: string
    payment_method_type: string
    driver_partner: string
    single_serve_flag: integer
    nps: string
    fe_assigned_flag: interger
    order_acceptance_flag: interger
    order_value_bucket: string
    user_paid_amount: double
    order_stage: string
    breach: string
    breach_time: string
    partition : 
    - dt: string
